### PR TITLE
enable waypoint on all browser sizes

### LINKED ISSUE #48: Fix overlap of Remind button and Planetary link on moible
image

### PR DESCRIPTION
**Pull request by ilikescience**
@singram26 plz review!

Closes #48.

### CODE REVIEW

**Comment by samblackk** [comment]
https://cl.ly/3n0Z133x3i3B check this out.. the content block jumps pretty badly on this PR.

**Comment by ilikescience** [comment]
@singram26 oh man this was a total #fail. My bad — working on it.

**Comment by ilikescience** [comment]
Ok @singram26 pull and test again please!

**Comment by samblackk** [comment]
@ilikescience lgtm

**Pull request merged**
