### PR TITLE
Content Updates from Issues

### LINKED ISSUE #14: typo in copy of first sentence
`first-rate friend` should be `first-rate friends`.

### PR DESCRIPTION
**Pull request by samblackk**
Closes #14, #15, #17, #18 
@ilikescience review plz.

### CODE REVIEW

**Comment by ilikescience** [comment]
@singram26 something about this branch is breaking the logo scroll behavior (works on dev)
scroll

**Comment by samblackk** [comment]
@ilikescience quite possibly z-index, I'll check into it.

**Comment by samblackk** [comment]
@ilikescience issue with the logo is fixed.

**Comment by ilikescience** [comment]
@singram26 good to go!

**Pull request merged**
