### PR TITLE
resolve svg scaling issue on mobile

### PR DESCRIPTION
**Pull request by ilikescience**
@endtwist plz test & merge.

### CODE REVIEW

**Comment by ilikescience** [comment]
@endtwist 🔔

**Comment by samblackk** [comment]
checking this right meow.

**Comment by samblackk** [comment]
Not sure if this is related to the scaling issue.. but the clocks are all over the place on iOS: 
http://cl.ly/1E0S351e261S
http://cl.ly/3E3y0U3m0D3D

**Comment by ilikescience** [comment]
@singram26 yech. I'll look into it — I'm not really even sure what's causing that problem. You're on a 5s, right?

**Comment by samblackk** [comment]
@ilikescience yes, 5s (iOS 8.4.1.) - viewed in Safari and Chrome.

**Comment by samblackk** [comment]
@ilikescience overflow fixed, please review it! 

this change also closes #22

**Comment by ilikescience** [comment]
🙌 awesome work.

**Pull request merged**
