### PR TITLE
Add can't come soon enough link

### LINKED ISSUE #33: "Can't come soon enough" doesn't link anywhere
screen shot 2016-06-23 at 11 05 39 am

### PR DESCRIPTION
**Pull request by ilikescience**
closes #33 

@endtwist plz review

### CODE REVIEW

**Comment by samblackk** [comment]
this may not be something to do this round, but we should design be a better way to show the gif without taking the user off the page.

**Comment by ilikescience** [comment]
Agreed! Just wanted to 🚢 first and ask questions later.

**Comment by samblackk** [comment]
okies @ilikescience rebase and i'll merge this in.

**Comment by ilikescience** [comment]
rebased.

**Pull request merged**
