### PR TITLE
Add Favicon

### LINKED ISSUE #19: Add favicon

### PR DESCRIPTION
**Pull request by samblackk**
Closes #19 ready for review!

### CODE REVIEW

**Comment by ilikescience** [comment]
@singram26 build:favicon / watch:favicon currently aren't in the default gulp task. Could you add them where appropriate?

**Comment by ilikescience** [comment]
@singram26 also, just noticed that the favicon in the assets folder isn't very hi-res, meaning the larger size favicons are blurry. Could you grab a higher-res image (ie larger than 96x96) from @vincejoyiv?

**Comment by samblackk** [comment]
@ilikescience updates are completed.

**Comment by ilikescience** [comment]
@singram26 Looks great. Good work!

**Pull request merged**
